apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "superapp-integration-service.fullname" . }}
  labels:
    {{- include "superapp-integration-service.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "superapp-integration-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "superapp-integration-service.selectorLabels" . | nindent 8 }}
    spec:
      hostAliases:
       - ip: "101.0.205.11"
         hostnames:
         - "hdp-master-01.local.com"
       - ip: "101.0.205.12"
         hostnames:
         - "hdp-master-02.local.com"
       - ip: "101.0.205.15"
         hostnames:
         - "hdp-worker-01.local.com"
       - ip: "101.0.205.16"
         hostnames:
         - "hdp-worker-02.local.com"
       - ip: "101.0.205.17"
         hostnames:
         - "hdp-worker-03.local.com"
       - ip: "101.0.205.18"
         hostnames:
         - "hdp-worker-04.local.com"
       - ip: "101.0.205.19"
         hostnames:
         - "hdp-worker-05.local.com"
       - ip: "101.0.205.13"
         hostnames:
         - "hdp-kafka-01.local.com"
       - ip: "101.0.205.14"
         hostnames:
         - "hdp-kafka-02.local.com"
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.serviceAccount.create }}{{ .Values.serviceAccount.name }}{{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh","-c", "/home/developer/entrypoint.sh"]
          ports:
            - name: http
              containerPort: {{ .Values.ports.containerPort }}
              protocol: TCP
          {{- if .Values.readinessProbe.enable }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.ports.containerPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{- if .Values.livenessProbe.enable }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.ports.containerPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resourcesLimits.cpu }}
              memory: {{ .Values.resourcesLimits.memory }}
            requests:
              cpu: {{ .Values.requestsResources.cpu }}
              memory: {{ .Values.requestsResources.memory }}
           
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
          env:
          - name: MYSQL_URL
            value: {{ .Values.env.mysqlUrl }}
          - name: MINIO_URL
            value: {{ .Values.env.minioUrl}}
          - name: MINIO_USER
            value: {{ .Values.env.minioUser}}
          - name: MINIO_PASS
            value: {{ .Values.env.minioPass}}
          {{- if .Values.collectServer.register }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash","{{ .Values.collectServer.postStartScript }}"]
            {{- if .Values.collectServer.preStopEnable }}
            preStop:
              exec:
                command: ["/bin/bash","{{ .Values.collectServer.preStopScript }}"]
            {{- end }}
          {{- end }}
          #~ - name: configmap
            #~ mountPath: /opt/enttribe/fiberneo/application.properties
            #~ subPath: "application.properties"  
              #          - name: configmap
            #            mountPath: /opt/bootnext/fiberneo-build/application.properties
              #              subPath: "application.properties" 
#          - name: {{ .Values.volumeName.hbaseConfig }}
#            mountPath: {{ .Values.volumeMounts.hbasePath }}
      volumes:
      - name: configmap
        configMap:
          name: {{ include "superapp-integration-service.fullname" . }}-configmap
      - name: shared-vol1
#        nfs:
 #         server: {{ .Values.volumes.nfsServerUrl }} 
  #        path: {{ .Values.volumes.nfsServerPath }}
#      - name: shared-vol2
#        nfs:
#          server: {{ .Values.volumes.nfsServerUrl }}
#          path: {{ .Values.volumes.nfsProtectedPath }}
#      - name: configmap
#        configMap:
#          name: {{ include "superapp-integration-service.fullname" . }}-configmap
#      - name: {{ .Values.volumeName.hbaseConfig }}
#        configMap:
#          defaultMode: {{ .Values.configMap.defaultMode }}
#          name: {{ .Values.volumes.hbaseConfigmapName }}
