export class CustomTemplateConstant {
    static readonly APP_NAME = 'EVFORGE_APP_NAME';
    static readonly WAREHOUSE_CONFIG_KEY = 'EVTRIUM_ALL_WAREHOUSE_DASHBOARD_DATA';
    static readonly WAREHOUSE_MANAGEMENT_CONFIG_DASHBOARD = 'EVTRIUM_WAREHOUSE_MANAGEMENT_DASHBOARD';
    static readonly WAREHOUSE_CONFIG_DASHBOARD = 'EVTRIUM_SINGLE_WAREHOUSE_DASHBOARD';
    static readonly LOGISTICS_CONFIG_DASHBOARD = 'EVTRIUM_LOGISTICS_DASHBOARD_DATA';
    static readonly MATERIAL_MANAGEMENT_CONFIG_DASHBOARD= 'EVTRIUM_MATERIAL_MANAGEMENT_DASHBOARD_DATA';
    static readonly PROCUREMENT_CONFIG_DASHBOARD= 'EVTRIUM_PROCUREMENT_DASHBOARD_DATA';
    static readonly WAREHOUSE_PLANNING_CONFIG= 'EVTRIUM_WAREHOUSE_PLANNING';   
}

