{{- if .Values.gateway.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gw
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    istio: {{ .Values.gateway.name }}
  servers:
  - port:
      number: {{ .Values.gatewayServers.portNumber }}
      name: {{ .Values.gatewayServers.portName }}
      protocol: {{.Values.gatewayServers.portProtocol }}
    hosts:
    - {{ .Values.gatewayServers.hosts }}
{{- end }}
